### ISSUE TITLE
`Unexpected argument: gen-jni-library`

### ISSUE THREAD

**Issue by mccartney** [oyvindberg/tui-scala#55]
When trying [the current master's contributing instructions](https://github.com/oyvindberg/tui-scala/blob/f3e7322ebbb518cf9005f8e6111d25e02d974f54/contributing.md) one of the steps fails:
> bleep gen-jni-library to generate JNI bindings for crossterm (needed to run)

yields
```
➜  tui-scala git:(master) bleep gen-jni-library
📗 Launching Bleep version 0.0.1-M27 as requested in /private/tmp/tui-scala/bleep.yaml
📗 bootstrapped in 9 ms
Unexpected argument: gen-jni-library

Usage:
    bleep [--no-color] [--debug] [--directory <string>] [--dev] [--no-bsp-progress] [--log-as-json] build
[...]
```
on my computer (running OSX Ventura, EDIT: same in Ubuntu)

**Comment by oyvindberg** [comment]
err no, it was on purpose actually. it's setup as a sourcegen thing now, so you only need to say bleep compile and it'll run if needed. we should update docs instead

**Comment by oyvindberg** [comment]
you can run it manually if you want/need by saying `bleep sourcegen`

**Comment by mccartney** [comment]
Thanks for looking into it! Suggesting #56, not sure if it's enough.
