### ISSUE TITLE
migrate from tui-rs to ratatui

### ISSUE THREAD

**Issue by Jedsek** [oyvindberg/tui-scala#62]
tui-rs is no longer updated,and ratatui is more activated version instead for it

https://ratatui.rs/introduction/

**Comment by nightscape** [comment]
As far as I understand this library is a port of tui-rs and doesn't use it.

**Comment by Jedsek** [comment]
from tui-rs README
> ⚠️ August 2023: This crate is no longer maintained. See https://github.com/ratatui-org/ratatui for an actively maintained fork. ⚠️

**Comment by oyvindberg** [comment]
It would be lovely to forward-port changes from that fork to `tui-scala`. 

I don't have the bandwidth to look into it anytime soon, but would be happy to mentor anyone who want to give it a shot. This codebase is still very similar to `tui-rs`, so I'd imagine many changes would be 1-1 translation of rust
